### ISSUE TITLE
ホモサピエンスの生態について

### ISSUE THREAD

**Issue by yasu80** [tanacchi/HomoSapiens#1]
僕の知っているホモサピエンスは二足歩行なのですが, READMEには四足歩行の生物が描かれています. 

これは要件定義のエラーではないのでしょうか? 対応おねがいします

**Comment by tanacchi** [comment]
@yasu80 
誰も README に描かれている生物がホモ・サピエンスとは申しておりません。
あれは「ﾎﾓｫ...」ですよ。文字化けにより出現しているだけなので気にしなくておｋです。
そのうち対処いたします。

**Comment by tanacchi** [comment]
まあ深夜テンションということで。
閉じー
